/* fund_warp.cpp — v4 wedge-fold warp vs the hhg9 fold build (frozen
 * Python reference, wedge-CT §3.7b).
 *
 * Loads core/Sphere_l6_fund.f64g.h9warp, builds the fund WarpState
 * (wedge + reflection halos, shipped gradients — no estimation), and
 * checks warp_do / warp_undo against test_data/fund_warp_ref.bin
 * (10,200 rows over interior, on-edge, near-edge, near-mirror,
 * near-corner and equator points, both modes, generated by
 * tools/support/gen_fund_warp_ref.py).
 *
 * Expected agreement: same values + same gradients + same triangle set
 * + same CT formula ⇒ field parity at float noise (v3 precedent:
 * 2.3e-15 over 50k). Newton details differ slightly from Python
 * (identity seed vs inv_linear seed), but both converge to the same
 * root: undo bound 1e-12; internal RT must hold at ~1e-14.
 */
#include "../core/h9_warp.h"

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <vector>

#ifndef H9_REPO_DIR
#define H9_REPO_DIR "."
#endif

int main(void)
{
    const std::string repo = H9_REPO_DIR;
    std::string err;
    h9::WarpState ws;
    if (!h9::load_h9warp(repo + "/core/Sphere_l6_fund.f64g.h9warp",
                         ws.data, &err)) {
        std::printf("FAIL: load: %s\n", err.c_str());
        return 1;
    }
    if (!ws.data.fund || !ws.data.has_gradients()) {
        std::printf("FAIL: blob not v4-fund-with-gradients\n");
        return 1;
    }
    if (!h9::finish_warp_state(ws)) {
        std::printf("FAIL: finish_warp_state\n");
        return 1;
    }
    /* fund field runs raw (no feather, no bypass) — hhg9 parity. */
    ws.edge_feather = false;
    ws.edge_bypass  = false;
    std::printf("fund state: %zu wedge verts, %zu padded, %zu tris, fold=%d\n",
                (std::size_t)ws.mesh.n_interior_verts,
                ws.mesh.padded_src.size(), ws.mesh.tris.size(), (int)ws.fold);

    if (std::getenv("H9_FUND_DUMP")) {
        std::ofstream out(std::string(std::getenv("H9_FUND_DUMP")),
                          std::ios::binary);
        const std::int64_t np = (std::int64_t)ws.mesh.padded_src.size();
        out.write(reinterpret_cast<const char*>(&np), 8);
        /* rows: x, y, dx, dy, gdx0, gdx1, gdy0, gdy1 — via the CT coeff
         * inputs is awkward; rebuild the padded grads the same way the
         * finish path did. */
        std::vector<std::array<double, 2>> gdx2, gdy2;
        h9::WarpMesh m2;
        h9::FundGeom fg2;
        h9::build_fund_mesh(ws.data, m2, gdx2, gdy2, fg2, nullptr);
        for (std::size_t i = 0; i < m2.padded_src.size(); ++i) {
            double row[8] = {m2.padded_src[i][0], m2.padded_src[i][1],
                             m2.padded_diff[i][0], m2.padded_diff[i][1],
                             gdx2[i][0], gdx2[i][1], gdy2[i][0], gdy2[i][1]};
            out.write(reinterpret_cast<const char*>(row), 64);
        }
        std::printf("dumped %lld padded rows\n", (long long)np);
    }

    std::ifstream fh(repo + "/test_data/fund_warp_ref.bin", std::ios::binary);
    if (!fh) {
        std::printf("FAIL: cannot open fund_warp_ref.bin\n");
        return 1;
    }
    std::int64_t n = 0;
    fh.read(reinterpret_cast<char*>(&n), 8);
    std::vector<double> rows(static_cast<std::size_t>(n) * 8);
    fh.read(reinterpret_cast<char*>(rows.data()),
            static_cast<std::streamsize>(rows.size() * 8));
    if (!fh) {
        std::printf("FAIL: short read on fund_warp_ref.bin\n");
        return 1;
    }

    int fails = 0;
    double worst_do = 0.0, worst_undo = 0.0, worst_rt = 0.0;
    std::int64_t worst_do_i = -1;
    for (std::int64_t i = 0; i < n; ++i) {
        const double* r = &rows[static_cast<std::size_t>(i) * 8];
        const double x = r[0], y = r[1];
        const int mo = static_cast<int>(r[2]);
        double wx, wy;
        h9::warp_do(ws, x, y, mo, &wx, &wy);
        const double d_do = std::fmax(std::fabs(wx - r[3]),
                                      std::fabs(wy - r[4]));
        if (d_do > worst_do) { worst_do = d_do; worst_do_i = i; }

        double rx, ry;
        h9::warp_undo(ws, r[3], r[4], mo, &rx, &ry);
        const double d_un = std::fmax(std::fabs(rx - r[5]),
                                      std::fabs(ry - r[6]));
        if (d_un > worst_undo) worst_undo = d_un;

        /* internal round trip through the C evaluators */
        double bx, by;
        h9::warp_undo(ws, wx, wy, mo, &bx, &by);
        const double d_rt = std::fmax(std::fabs(bx - x), std::fabs(by - y));
        if (d_rt > worst_rt) worst_rt = d_rt;
    }
    if (worst_do > 2e-14 && worst_do_i >= 0) {
        const double* r = &rows[static_cast<std::size_t>(worst_do_i) * 8];
        std::printf("worst do row %lld: x=%+.8f y=%+.8f mo=%d\n",
                    (long long)worst_do_i, r[0], r[1], (int)r[2]);
        /* histogram of do errors above thresholds */
        int n8 = 0, n10 = 0, n12 = 0, n14 = 0;
        for (std::int64_t i = 0; i < n; ++i) {
            const double* q = &rows[static_cast<std::size_t>(i) * 8];
            double wx2, wy2;
            h9::warp_do(ws, q[0], q[1], (int)q[2], &wx2, &wy2);
            const double d = std::fmax(std::fabs(wx2 - q[3]),
                                       std::fabs(wy2 - q[4]));
            if (d > 1e-8)  ++n8;
            if (d > 1e-10) ++n10;
            if (d > 1e-12) ++n12;
            if (d > 1e-14) ++n14;
        }
        std::printf("do err histogram: >1e-8:%d  >1e-10:%d  >1e-12:%d  >1e-14:%d  (of %lld)\n",
                    n8, n10, n12, n14, (long long)n);
    }
    std::printf("warp_do  vs python: worst %.3e %s\n", worst_do,
                worst_do <= 2e-14 ? "PASS" : "FAIL");
    if (worst_do > 2e-14) ++fails;
    std::printf("warp_undo vs python: worst %.3e %s\n", worst_undo,
                worst_undo <= 1e-12 ? "PASS" : "FAIL");
    if (worst_undo > 1e-12) ++fails;
    std::printf("C round trip:       worst %.3e %s\n", worst_rt,
                worst_rt <= 1e-13 ? "PASS" : "FAIL");
    if (worst_rt > 1e-13) ++fails;

    std::printf(fails ? "=== fund_warp: FAIL (%d) ===\n"
                      : "=== fund_warp: PASS ===\n", fails);
    return fails ? 1 : 0;
}
