/* pole_seam.c — the addressing chain at its worst-conditioned points, vs the
 * hhg9 Python reference.
 *
 * Companion to via_sphere.c. That test samples the sphere broadly; this one
 * samples ONLY the hard places, densely: the polar approach (ε from 1e-12 to
 * 2 degrees off each pole), the poles themselves reached from every seam
 * meridian, the eight octant seams straddled at ±1e-13 and ±1e-9 degrees over
 * a latitude ladder that runs INTO the polar band, and the octant corners
 * (atan(1/√2) — the triple points where three faces and two seams meet).
 *
 * Why: the hhg9 pytests test the poles at exactly ±90
 * (test_octant_seams::test_poles_mode_only) and the seams only up to ±88
 * (test_seam_greenwich_bulk, which clamps explicitly "to avoid poles/
 * vertices"). The 88°..90° pole×seam interaction band is reached by neither —
 * and that band is where the seam, pole, tail and authalic bugs historically
 * lived. This test exists to keep it covered.
 *
 * Reference: test_data/pole_seam_ref.bin, generated by
 * tools/support/gen_pole_seam_ref.py from the pure-Python chain.
 *
 * Bounds match via_sphere.c: b_oct agreement ≤ 5e-13 units, round trip
 * ≤ 1e-11 deg, and oid must MATCH exactly — at a seam a wrong octant is a
 * frame bug, not noise.
 *
 * Round-trip error is measured as GREAT-CIRCLE separation, not as a lat/lon
 * component difference — see gc_sep_deg. Near the poles the two disagree by
 * orders of magnitude, and only the great-circle figure means anything.
 */
#include "hex9_c.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef H9_REPO_DIR
#define H9_REPO_DIR "."
#endif

#define MAX_REPORT 10

static int read_rows(const char *path, double **rows, long long *n)
{
    FILE *fh = fopen(path, "rb");
    if (!fh) return 0;
    if (fread(n, 8, 1, fh) != 1) { fclose(fh); return 0; }
    *rows = (double *)malloc((size_t)(*n) * 8 * sizeof(double));
    if (!*rows) { fclose(fh); return 0; }
    const size_t got = fread(*rows, sizeof(double), (size_t)(*n) * 8, fh);
    fclose(fh);
    return got == (size_t)(*n) * 8;
}

/* Great-circle separation of two lon/lat points, in DEGREES of arc.
 *
 * This, not a lat/lon component difference, is the correct error metric here.
 * Near a pole longitude is arbitrarily ill-conditioned: at 1.6e-12 deg from
 * the pole (~0.18 um) a 1-ULP wobble in the cartesian coordinates swings the
 * recovered longitude by whole degrees, while the point itself has moved
 * picometres. Comparing |dlon| there measures the coordinate system's
 * singularity, not the projection's accuracy. Haversine measures the thing we
 * actually care about — did the point come back to where it started — and is
 * well-conditioned everywhere including at the poles, so it needs no
 * special-casing for them.
 */
static double gc_sep_deg(double lon_a, double lat_a, double lon_b, double lat_b)
{
    const double D = M_PI / 180.0;
    const double p1 = lat_a * D, p2 = lat_b * D;
    const double dp = (lat_b - lat_a) * D;
    const double dl = (lon_b - lon_a) * D;
    const double s1 = sin(dp * 0.5), s2 = sin(dl * 0.5);
    double a = s1 * s1 + cos(p1) * cos(p2) * s2 * s2;
    if (a < 0.0) a = 0.0;
    if (a > 1.0) a = 1.0;
    return 2.0 * asin(sqrt(a)) / D;
}

int main(void)
{
    char err[256] = {0};
    if (hex9_warp_init(err, sizeof err)) {
        printf("FAIL: warp init: %s\n", err);
        return 1;
    }

    double *rows = NULL;
    long long n = 0;
    if (!read_rows(H9_REPO_DIR "/test_data/pole_seam_ref.bin", &rows, &n)) {
        printf("FAIL: cannot read pole_seam_ref.bin\n");
        return 1;
    }

    int fails = 0, oid_bad = 0, reported = 0;
    double worst_fwd = 0.0, worst_rt = 0.0, worst_prt = 0.0;
    double worst_fwd_lat = 0.0, worst_fwd_lon = 0.0;
    double worst_rt_lat = 0.0, worst_rt_lon = 0.0;
    double worst_prt_lat = 0.0, worst_prt_lon = 0.0;

    for (long long i = 0; i < n; ++i) {
        const double *r = &rows[i * 8];
        const double lon = r[0], lat = r[1];
        const double ref_cx = r[2], ref_cy = r[3];
        const int    ref_oid = (int)r[4];
        const double ref_rt_lon = r[5], ref_rt_lat = r[6];

        double cx, cy;
        int oid;
        if (hex9_project(lon, lat, &cx, &cy, &oid)) {
            printf("FAIL: project error at (%.15g, %.15g)\n", lon, lat);
            ++fails; continue;
        }

        const double dfwd = fabs(cx - ref_cx) + fabs(cy - ref_cy);
        if (dfwd > worst_fwd) {
            worst_fwd = dfwd; worst_fwd_lat = lat; worst_fwd_lon = lon;
        }

        if (oid != ref_oid) {
            ++oid_bad;
            if (reported++ < MAX_REPORT)
                printf("FAIL oid at (%.15g, %.15g): want %d got %d\n",
                       lon, lat, ref_oid, oid);
        }

        /* C round trip through our own projection. */
        double rt_lon, rt_lat;
        if (hex9_unproject(cx, cy, oid, &rt_lon, &rt_lat)) {
            printf("FAIL: unproject error at (%.15g, %.15g)\n", lon, lat);
            ++fails; continue;
        }
        const double drt = gc_sep_deg(lon, lat, rt_lon, rt_lat);
        if (drt > worst_rt) {
            worst_rt = drt; worst_rt_lat = lat; worst_rt_lon = lon;
        }

        /* Our unproject vs Python's. */
        const double dprt = gc_sep_deg(ref_rt_lon, ref_rt_lat, rt_lon, rt_lat);
        if (dprt > worst_prt) {
            worst_prt = dprt; worst_prt_lat = lat; worst_prt_lon = lon;
        }
    }

    printf("rows: %lld\n", n);
    printf("oid mismatches: %d %s\n", oid_bad, oid_bad ? "FAIL" : "PASS");
    if (oid_bad) ++fails;
    printf("b_oct fwd vs python: worst %.3e %s  (at lon %.15g lat %.15g)\n",
           worst_fwd, worst_fwd <= 5e-13 ? "PASS" : "FAIL",
           worst_fwd_lon, worst_fwd_lat);
    if (worst_fwd > 5e-13) ++fails;
    printf("C round trip (deg):  worst %.3e %s  (at lon %.15g lat %.15g)\n",
           worst_rt, worst_rt <= 1e-11 ? "PASS" : "FAIL",
           worst_rt_lon, worst_rt_lat);
    if (worst_rt > 1e-11) ++fails;
    printf("unproject vs python: worst %.3e deg %s  (at lon %.15g lat %.15g)\n",
           worst_prt, worst_prt <= 1e-11 ? "PASS" : "FAIL",
           worst_prt_lon, worst_prt_lat);
    if (worst_prt > 1e-11) ++fails;

    free(rows);
    printf(fails ? "=== pole_seam: FAIL (%d) ===\n"
                 : "=== pole_seam: PASS ===\n", fails);
    return fails ? 1 : 0;
}
