/* via_sphere.c — end-to-end via-sphere chain vs the hhg9 Python reference.
 *
 * Enables hex9_set_via_sphere(1) (authalic series front-end + unit-sphere
 * core + Sphere-L6 wedge-fold warp) and checks hex9_project /
 * hex9_unproject against test_data/via_sphere_ref.bin (4,010 rows:
 * seeded random + landmarks incl. ±89.9999° and near-seam points,
 * generated by tools/support/gen_via_sphere_ref.py from the frozen
 * pure-Python via-sphere chain).
 *
 * Bounds: b_oct agreement ≤ 5e-13 units (~12 µm ground; the AK solves
 * differ Gauss-Newton vs Python's inverse, both drive to the float
 * floor), C round trip ≤ 1e-11 deg (~1 mm), and oid must MATCH — a
 * wrong octant is a chain bug, not noise. Toggling back to classic must
 * reproduce the classic numbers (mode isolation).
 */
#include "hex9_c.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef H9_REPO_DIR
#define H9_REPO_DIR "."
#endif

static int read_rows(const char *path, double **rows, long long *n)
{
    FILE *fh = fopen(path, "rb");
    if (!fh) return 0;
    if (fread(n, 8, 1, fh) != 1) { fclose(fh); return 0; }
    *rows = (double *)malloc((size_t)(*n) * 8 * sizeof(double));
    const size_t got = fread(*rows, sizeof(double), (size_t)(*n) * 8, fh);
    fclose(fh);
    return got == (size_t)(*n) * 8;
}

int main(void)
{
    char err[256] = {0};
    if (hex9_warp_init(err, sizeof err)) {
        printf("FAIL: warp init: %s\n", err);
        return 1;
    }
    if (hex9_set_via_sphere(1, err, sizeof err)) {
        printf("FAIL: via-sphere init: %s\n", err);
        return 1;
    }

    double *rows = NULL;
    long long n = 0;
    if (!read_rows(H9_REPO_DIR "/test_data/via_sphere_ref.bin", &rows, &n)) {
        printf("FAIL: cannot read via_sphere_ref.bin\n");
        return 1;
    }

    int fails = 0, oid_bad = 0;
    double worst_fwd = 0.0, worst_rt = 0.0, worst_prt = 0.0;
    for (long long i = 0; i < n; ++i) {
        const double *r = &rows[i * 8];
        double cx, cy;
        int oid;
        hex9_project(r[0], r[1], &cx, &cy, &oid);
        if (oid != (int)r[4]) { ++oid_bad; continue; }
        const double df = fmax(fabs(cx - r[2]), fabs(cy - r[3]));
        if (df > worst_fwd) worst_fwd = df;

        /* C round trip (project -> unproject) in degrees */
        double lon2, lat2;
        hex9_unproject(cx, cy, oid, &lon2, &lat2);
        double dlon = fabs(lon2 - r[0]);
        if (dlon > 180.0) dlon = fabs(dlon - 360.0);
        /* longitude degenerates at the poles — weight by cos(lat) */
        const double rt = fmax(dlon * cos(r[1] * M_PI / 180.0),
                               fabs(lat2 - r[1]));
        if (rt > worst_rt) worst_rt = rt;

        /* vs the Python round trip of the same b_oct point */
        double lon3, lat3;
        hex9_unproject(r[2], r[3], oid, &lon3, &lat3);
        double dl3 = fabs(lon3 - r[5]);
        if (dl3 > 180.0) dl3 = fabs(dl3 - 360.0);
        const double prt = fmax(dl3 * cos(r[6] * M_PI / 180.0),
                                fabs(lat3 - r[6]));
        if (prt > worst_prt) worst_prt = prt;
    }
    printf("oid mismatches: %d %s\n", oid_bad, oid_bad == 0 ? "PASS" : "FAIL");
    if (oid_bad) ++fails;
    printf("b_oct fwd vs python: worst %.3e %s\n", worst_fwd,
           worst_fwd <= 5e-13 ? "PASS" : "FAIL");
    if (worst_fwd > 5e-13) ++fails;
    printf("C round trip (deg):  worst %.3e %s\n", worst_rt,
           worst_rt <= 1e-11 ? "PASS" : "FAIL");
    if (worst_rt > 1e-11) ++fails;
    printf("unproject vs python: worst %.3e deg %s\n", worst_prt,
           worst_prt <= 1e-11 ? "PASS" : "FAIL");
    if (worst_prt > 1e-11) ++fails;

    /* mode isolation: classic numbers must be restored on toggle-off */
    hex9_set_via_sphere(0, err, sizeof err);
    double cx0, cy0;
    int oid0;
    hex9_project(-3.19, 55.95, &cx0, &cy0, &oid0);
    if (hex9_set_via_sphere(1, err, sizeof err)) {
        printf("FAIL: via-sphere re-enable\n");
        return 1;
    }
    double cx1, cy1;
    int oid1;
    hex9_project(-3.19, 55.95, &cx1, &cy1, &oid1);
    hex9_set_via_sphere(0, err, sizeof err);
    double cx2, cy2;
    int oid2;
    hex9_project(-3.19, 55.95, &cx2, &cy2, &oid2);
    const int iso_ok = (cx0 == cx2) && (cy0 == cy2) && (oid0 == oid2) &&
                       (fabs(cx1 - cx0) + fabs(cy1 - cy0) > 1e-9);
    printf("mode isolation: %s\n", iso_ok ? "PASS" : "FAIL");
    if (!iso_ok) ++fails;

    free(rows);
    printf(fails ? "=== via_sphere: FAIL (%d) ===\n"
                 : "=== via_sphere: PASS ===\n", fails);
    return fails ? 1 : 0;
}
