/* Generated by tools/gen_e4h_tables.py from hhg9 b70eeac — do not edit.
 *
 * E4H (aperture-4 structural tail) frozen tables. The integer
 * tables define the EXACT classifier in Z[1/2, sqrt3]; the FP
 * tables are the det-math seed. Regenerating with different
 * values is a regime change for E4H addresses (universality.md).
 */
#pragma once
#include <stdint.h>

#define E4H_MARK   0xE
#define E4H_SIGMA  46   /* snap: W = llround(w * 2^SIGMA) */
#define E4H_BITS_BOUND 113 /* worst-case component bits, rigorous */
#if E4H_BITS_BOUND > 120
#error "E4H descent component bound exceeds __int128 comfort"
#endif

/* rep-4 child rotations (units of 60 deg) and the piece inversion
 * P3[(class - s) mod 3] -> piece index (reference _ROT3_PIECE). */
static const int E4H_ROT[4] = {0, 2, 3, 4};
static const int E4H_P3[3] = {2, 3, 1};

/* five-symbol bases: BASES[oid][slot] (axis->digit gauge baked in) */
static const int E4H_BASES[8][3] = {
    {5, 2, 3},
    {3, 4, 2},
    {4, 3, 5},
    {2, 5, 4},
    {5, 2, 4},
    {3, 4, 5},
    {4, 3, 2},
    {2, 5, 3},
};

/* child maps as u = M_k (w - B_k): M integer Z[sqrt3] components
 * (rA, rB, iA, iB) with value (rA + rB*s3) + i(iA + iB*s3);
 * B at fixed scale /4. Exactly (w - b_k)/a_k. */
static const int64_t E4H_M[4][4] = {
    {2, 0, 0, 0},
    {-1, 0, 0, -1},
    {-2, 0, 0, 0},
    {-1, 0, 0, 1},
};
static const int64_t E4H_B4[4][4] = {   /* value = B4/4 */
    {0, 0, 0, 0},
    {0, -1, 3, 0},
    {0, -2, 0, 0},
    {0, -1, -3, 0},
};
static const int E4H_HALF_SIGN[2] = {1, -1};

/* trapezoid edges for the signed-distance score: 2*p and 2*e as
 * integer Z[sqrt3] quadruples (score sign/order is scale-free). */
static const int64_t E4H_EDGE_P2[4][4] = {
    {0, 0, 2, 0},
    {0, -1, 1, 0},
    {0, -1, -1, 0},
    {0, 0, -2, 0},
};
static const int64_t E4H_EDGE_E2[4][4] = {
    {0, -1, -1, 0},
    {0, 0, -2, 0},
    {0, 1, -1, 0},
    {0, 0, 2, 0},
};

/* state frames A[p_mo][c2] (complex): w = A*3^layer*conj(z - c) */
static const double E4H_A_RE[2][3] = {
    {0x1.d64d51e0db1c8p+0, 0x1.14ab16edd8115p-52, -0x1.d64d51e0db1c7p+0},
    {-0x1.d64d51e0db1c6p+0, 0x1.4e459de1933d6p-52, 0x1.d64d51e0db1c6p+0},
};
static const double E4H_A_IM[2][3] = {
    {0x1.0f876ccdf6cdbp+0, -0x1.0f876ccdf6cd9p+1, 0x1.0f876ccdf6cdbp+0},
    {-0x1.0f876ccdf6cdap+0, 0x1.0f876ccdf6cdap+1, -0x1.0f876ccdf6cdap+0},
};

/* decode probes: canonical trapezoid centroid and its partner */
static const double E4H_CEN_RE = -0x1.8a2345cc04426p-2;   /* -2/(3*sqrt3) */
static const double E4H_CEN_IM = 0x0.0p+0;

/* octant seam algebra per (mode, corner k): sv triangles (CW),
 * the crossed axis bit, and the unfold/fold affines ([x y 1] @ m).
 * Unfold: neighbour-frame point -> this frame; fold: inverse. */
static const double E4H_SV[2][3][2] = {
    {{0x1.6a09e667f3bccp-1, 0x1.a20bd700c2c3dp-2}, {0x0.0p+0, -0x1.a20bd700c2c3dp-1}, {-0x1.6a09e667f3bccp-1, 0x1.a20bd700c2c3dp-2}},
    {{0x1.6a09e667f3bccp-1, -0x1.a20bd700c2c3dp-2}, {-0x1.6a09e667f3bccp-1, -0x1.a20bd700c2c3dp-2}, {0x0.0p+0, 0x1.a20bd700c2c3dp-1}},
};
static const int E4H_AXK[2][3] = {{0, 2, 1}, {0, 1, 2}};
static const double E4H_UNF[2][3][3][2] = {
  {
    {{-0x1.0000000000000p-1, -0x1.bb67ae8584caap-1}, {0x1.bb67ae8584caap-1, -0x1.0000000000000p-1}, {-0x1.6a09e667f3bccp-1, -0x1.a20bd700c2c3dp-2}},
    {{0x1.0000000000000p+0, -0x0.0p+0}, {-0x0.0p+0, 0x1.0000000000000p+0}, {0x0.0p+0, 0x1.a20bd700c2c3dp-1}},
    {{-0x1.0000000000000p-1, 0x1.bb67ae8584caap-1}, {-0x1.bb67ae8584caap-1, -0x1.0000000000000p-1}, {0x1.6a09e667f3bccp-1, -0x1.a20bd700c2c3dp-2}},
  },
  {
    {{-0x1.0000000000000p-1, 0x1.bb67ae8584caap-1}, {-0x1.bb67ae8584caap-1, -0x1.0000000000000p-1}, {-0x1.6a09e667f3bccp-1, 0x1.a20bd700c2c3dp-2}},
    {{-0x1.0000000000000p-1, -0x1.bb67ae8584caap-1}, {0x1.bb67ae8584caap-1, -0x1.0000000000000p-1}, {0x1.6a09e667f3bccp-1, 0x1.a20bd700c2c3dp-2}},
    {{0x1.0000000000000p+0, 0x0.0p+0}, {0x0.0p+0, 0x1.0000000000000p+0}, {0x0.0p+0, -0x1.a20bd700c2c3dp-1}},
  },
};
static const double E4H_FLD[2][3][3][2] = {
  {
    {{-0x1.0000000000001p-1, 0x1.bb67ae8584caap-1}, {-0x1.bb67ae8584caap-1, -0x1.0000000000000p-1}, {-0x1.6a09e667f3bccp-1, 0x1.a20bd700c2c3dp-2}},
    {{0x1.0000000000000p+0, -0x0.0p+0}, {0x0.0p+0, 0x1.0000000000000p+0}, {0x0.0p+0, -0x1.a20bd700c2c3dp-1}},
    {{-0x1.ffffffffffffdp-2, -0x1.bb67ae8584ca9p-1}, {0x1.bb67ae8584caap-1, -0x1.ffffffffffffep-2}, {0x1.6a09e667f3bcap-1, 0x1.a20bd700c2c3dp-2}},
  },
  {
    {{-0x1.ffffffffffffdp-2, -0x1.bb67ae8584ca9p-1}, {0x1.bb67ae8584caap-1, -0x1.ffffffffffffep-2}, {-0x1.6a09e667f3bcap-1, -0x1.a20bd700c2c3dp-2}},
    {{-0x1.0000000000001p-1, 0x1.bb67ae8584caap-1}, {-0x1.bb67ae8584caap-1, -0x1.0000000000000p-1}, {0x1.6a09e667f3bccp-1, -0x1.a20bd700c2c3dp-2}},
    {{0x1.0000000000000p+0, 0x0.0p+0}, {-0x0.0p+0, 0x1.0000000000000p+0}, {0x0.0p+0, 0x1.a20bd700c2c3dp-1}},
  },
};
