#!/usr/bin/env python3
"""
export_ct_grads.py — export CT gradient arrays for the authalic warp grid.

Evaluates the four partial-derivative grids:
    ∂(warp_dx)/∂x,  ∂(warp_dx)/∂y,
    ∂(warp_dy)/∂x,  ∂(warp_dy)/∂y

at every point of the existing N×N warp grid using fine-step (eps=1e-7) finite
differences on the CloughTocher2D interpolator.  These gradients let the C++
h9_ct_eval() function reproduce the CT cubic exactly within each grid triangle
(g = -1/2 for all regular right-triangle grid cells — no neighbour lookup needed).

Run from the hex9_cli source directory:
    python export_ct_grads.py

Output: h9_wgs84_warp_grads.h  (same directory)
Must match H9_WARP_N in h9_wgs84_warp_data.h.
"""

import os, math, datetime
import numpy as np
from scipy.interpolate import CloughTocher2DInterpolator, NearestNDInterpolator

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
NPZ_PATH   = os.path.join(SCRIPT_DIR, 'WGS84_l5_warp_data.npz')
OUT_PATH   = os.path.join(SCRIPT_DIR, 'h9_wgs84_warp_grads.h')

# N must match the value in h9_wgs84_warp_data.h
N     = 729
X_MIN = -math.sqrt(2.0) / 2.0
X_MAX =  math.sqrt(2.0) / 2.0
Y_MIN = -math.sqrt(6.0) / 3.0
Y_MAX =  math.sqrt(6.0) / 6.0

# ── Load NPZ ──────────────────────────────────────────────────────────────────
print(f"Loading {os.path.normpath(NPZ_PATH)} ...")
repo = np.load(NPZ_PATH, allow_pickle=True)
src  = repo['source_pts']
dst  = repo['target_pts']
diff = dst - src
print(f"  {len(src)} source/target pairs")

# ── Ghost-row padding (strict band — same as octahedral_barycentric.py) ──────
Y_EQ = math.sqrt(6.0) / 6.0
delta_y = Y_EQ - src[:, 1]
eq_band_mask = (delta_y > 0.0) & (delta_y < 0.05)
if np.any(eq_band_mask):
    ghost_src        = src[eq_band_mask].copy()
    ghost_src[:, 1]  = 2.0 * Y_EQ - ghost_src[:, 1]
    ghost_diff       = diff[eq_band_mask].copy()
    ghost_diff[:, 1] *= -1.0
    padded_src  = np.vstack([src,  ghost_src])
    padded_diff = np.vstack([diff, ghost_diff])
    print(f"  Ghost padding: {np.sum(eq_band_mask)} → {len(padded_src)} total")
else:
    padded_src  = src
    padded_diff = diff

# ── Build CT interpolators ────────────────────────────────────────────────────
print("Building CloughTocher2D interpolators ...")
ct_dx = CloughTocher2DInterpolator(padded_src, padded_diff[:, 0])
ct_dy = CloughTocher2DInterpolator(padded_src, padded_diff[:, 1])
nn_dx = NearestNDInterpolator(src, diff[:, 0])
nn_dy = NearestNDInterpolator(src, diff[:, 1])

def fwd_dx(xy):
    d = ct_dx(xy)
    m = np.isnan(d) & np.isfinite(xy).all(axis=1)
    if np.any(m): d[m] = nn_dx(xy[m])
    return d

def fwd_dy(xy):
    d = ct_dy(xy)
    m = np.isnan(d) & np.isfinite(xy).all(axis=1)
    if np.any(m): d[m] = nn_dy(xy[m])
    return d

# ── Grid ──────────────────────────────────────────────────────────────────────
xs = np.linspace(X_MIN, X_MAX, N)
ys = np.linspace(Y_MIN, Y_MAX, N)
gx_grid, gy_grid = np.meshgrid(xs, ys)
pts = np.stack([gx_grid.ravel(), gy_grid.ravel()], axis=1)  # (N*N, 2)
print(f"\nGrid: {N}×{N} = {len(pts)} points")
print(f"  x ∈ [{X_MIN:.10f}, {X_MAX:.10f}]")
print(f"  y ∈ [{Y_MIN:.10f}, {Y_MAX:.10f}]")

# ── Gradient evaluation via fine-step FD on the CT interpolator ──────────────
EPS = 1e-7
print(f"\nEvaluating CT gradients (eps={EPS}) — 8 CT passes, ~{8*len(pts)//1_000_000}M evals ...")

def ct_grad(fn, label):
    dx_p = np.array([[EPS, 0.0]])
    dx_m = np.array([[-EPS, 0.0]])
    dy_p = np.array([[0.0,  EPS]])
    dy_m = np.array([[0.0, -EPS]])
    print(f"  {label}: +x"); fp_x = fn(pts + dx_p)
    print(f"  {label}: -x"); fm_x = fn(pts + dx_m)
    print(f"  {label}: +y"); fp_y = fn(pts + dy_p)
    print(f"  {label}: -y"); fm_y = fn(pts + dy_m)
    gx = ((fp_x - fm_x) / (2.0 * EPS)).reshape(N, N).astype(np.float32)
    gy = ((fp_y - fm_y) / (2.0 * EPS)).reshape(N, N).astype(np.float32)
    print(f"    gx ∈ [{gx.min():.6f}, {gx.max():.6f}]  "
          f"gy ∈ [{gy.min():.6f}, {gy.max():.6f}]  "
          f"NaN: {np.isnan(gx).sum()}/{np.isnan(gy).sum()}")
    return gx, gy

grid_dx_gx, grid_dx_gy = ct_grad(fwd_dx, "dx")
grid_dy_gx, grid_dy_gy = ct_grad(fwd_dy, "dy")

# ── Write header ──────────────────────────────────────────────────────────────
def format_float_array(arr, name, n):
    flat = arr.flatten()
    def fmt(v):
        if np.isnan(v): v = 0.0
        s = f"{v:.9g}"
        if '.' not in s and 'e' not in s and 'n' not in s:
            s += '.0'
        return s + 'f'
    rows = []
    for i in range(0, len(flat), 8):
        rows.append("    " + ", ".join(fmt(v) for v in flat[i:i+8]))
    return f"static const float {name}[{n*n}] = {{\n" + ",\n".join(rows) + "\n};"

print(f"\nWriting {os.path.normpath(OUT_PATH)} ...")
hdr = f"""\
/* h9_wgs84_warp_grads.h — AUTO-GENERATED by export_ct_grads.py — DO NOT EDIT
 *
 * Generated : {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}
 * N         : {N}  (must equal H9_WARP_N in h9_wgs84_warp_data.h)
 * eps       : {EPS}  (FD step used for CT gradient evaluation)
 *
 * CT gradient arrays for the authalic warp displacement.
 * Layout: row-major, iy=0 → y=Y_MIN, ix=0 → x=X_MIN.  Index: iy*N+ix.
 *
 *   h9_warp_dx_gx[i]  ∂(warp_dx)/∂x   h9_warp_dx_gy[i]  ∂(warp_dx)/∂y
 *   h9_warp_dy_gx[i]  ∂(warp_dy)/∂x   h9_warp_dy_gy[i]  ∂(warp_dy)/∂y
 *
 * Used by h9_ct_eval() in h9_math.h.  g=-1/2 for all regular right-triangle
 * grid cells (proven analytically), so no neighbour lookup is needed.
 */
#ifndef H9_WARP_GRADS_H
#define H9_WARP_GRADS_H

{format_float_array(grid_dx_gx, 'h9_warp_dx_gx', N)}

{format_float_array(grid_dx_gy, 'h9_warp_dx_gy', N)}

{format_float_array(grid_dy_gx, 'h9_warp_dy_gx', N)}

{format_float_array(grid_dy_gy, 'h9_warp_dy_gy', N)}

#endif /* H9_WARP_GRADS_H */
"""
with open(OUT_PATH, 'w') as f:
    f.write(hdr)
size_kb = os.path.getsize(OUT_PATH) / 1024
print(f"Done.  {size_kb:.0f} KB")
