#!/usr/bin/env python3
"""
export_uv_lattice.py — Export integer UV supercell constants to h9_uv_lattice.h.

Run from the hex9_cli directory:
  python3 export_uv_lattice.py

Reads H9P, H9C, H9R, H9O from the Python library and writes C constants
needed by the create_clipped port in lwgeom_hex9.cpp.
"""
import os, sys
import numpy as np

HHGG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'PyCharm', 'hex9')
sys.path.insert(0, HHGG_PATH)

from hhg9.h9 import H9P, H9C, H9R, H9O, H9K

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'h9_uv_lattice.h')

def fmt_int_array_1d(arr, name, typ='int'):
    vals = ', '.join(str(int(x)) for x in arr)
    return f'static const {typ} {name}[] = {{{vals}}};\n'

def fmt_int_array_2d(arr, name, typ='int'):
    rows = []
    for row in arr:
        vals = ', '.join(str(int(x)) for x in row)
        rows.append(f'    {{{vals}}}')
    inner = ',\n'.join(rows)
    return f'static const {typ} {name}[][{arr.shape[1]}] = {{\n{inner}\n}};\n'

def fmt_int_array_3d(arr, name, typ='int'):
    lines = [f'/* {name}: shape ({arr.shape[0]}, {arr.shape[1]}, {arr.shape[2]}) */']
    lines.append(f'static const {typ} {name}[{arr.shape[0]}][{arr.shape[1]}][{arr.shape[2]}][2] = {{')
    for i in range(arr.shape[0]):
        lines.append(f'    /* mode {i} */ {{')
        for j in range(arr.shape[1]):
            vals = ', '.join(f'{{{int(arr[i,j,k,0])}, {int(arr[i,j,k,1])}}}' for k in range(arr.shape[2]))
            lines.append(f'        /* c2={j} */ {{{vals}}},')
        lines.append('    },')
    lines.append('};\n')
    return '\n'.join(lines) + '\n'

# mode_ofs: H9C.off_uv indexed by H9R.downs and H9R.ups, with U*3
downs = np.asarray(H9R.downs)   # (9,) cell IDs
ups   = np.asarray(H9R.ups)     # (9,) cell IDs

mode_ofs_dn = H9C.off_uv[downs].astype(np.int64).copy()  # (9, 2)
mode_ofs_up = H9C.off_uv[ups  ].astype(np.int64).copy()  # (9, 2)
mode_ofs_dn[:, 0] *= 3   # polygon grid: U is 3U
mode_ofs_up[:, 0] *= 3

mode_child_dn = H9C.mode[downs].astype(np.int64)  # (9,) mode of each mode-0 child
mode_child_up = H9C.mode[ups  ].astype(np.int64)  # (9,) mode of each mode-1 child

# H9P.hi: (2, 3, 7, 2) int16
hi = H9P.hi.astype(np.int64)   # (mode, c2, vertex, uv)

# H9O tables
oid_mo = H9O.oid_mo.astype(np.int64)   # (8,)
oid_nb = H9O.oid_nb.astype(np.int64)   # (8, 3)

# Lattice constants
U1 = float(H9K.lattice.U)
V3 = float(3.0 * H9K.lattice.V)

with open(OUT, 'w') as f:
    f.write('/* h9_uv_lattice.h — auto-generated by export_uv_lattice.py — DO NOT EDIT */\n')
    f.write('#pragma once\n\n')

    f.write(f'/* U1 = H9K.lattice.U, V3 = 3 * H9K.lattice.V */\n')
    f.write(f'static const double H9_UV_U1 = {U1:.18g};\n')
    f.write(f'static const double H9_UV_V3 = {V3:.18g};\n\n')

    # octant mode (redundant with H9_OID_MO in h9_addressing.h but kept for self-containment)
    f.write('/* H9O.oid_mo: octant mode (0=down, 1=up) indexed by oid 0..7 */\n')
    f.write(fmt_int_array_1d(oid_mo, 'H9_OID_MO_UV'))
    f.write('\n')

    # octant neighbours (8 x 3): oid_nb[oid, c2] = neighbour oid for seam reflection
    f.write('/* H9O.oid_nb[oid][c2]: neighbour octant id for seam vertex reflection */\n')
    f.write(fmt_int_array_2d(oid_nb, 'H9_OID_NB'))
    f.write('\n')

    # mode-0 child UV offsets (U already *3) and their modes
    f.write('/* H9C.off_uv[H9R.downs] with U*3: child UV offsets for mode-0 supercell */\n')
    f.write(fmt_int_array_2d(mode_ofs_dn, 'H9_MODE0_OFS'))
    f.write('\n')
    f.write('/* H9C.mode[H9R.downs]: mode of each mode-0 child */\n')
    f.write(fmt_int_array_1d(mode_child_dn, 'H9_MODE0_CHILD_MODE'))
    f.write('\n')

    # mode-1 child UV offsets (U already *3) and their modes
    f.write('/* H9C.off_uv[H9R.ups] with U*3: child UV offsets for mode-1 supercell */\n')
    f.write(fmt_int_array_2d(mode_ofs_up, 'H9_MODE1_OFS'))
    f.write('\n')
    f.write('/* H9C.mode[H9R.ups]: mode of each mode-1 child */\n')
    f.write(fmt_int_array_1d(mode_child_up, 'H9_MODE1_CHILD_MODE'))
    f.write('\n')

    # H9P.hi (2, 3, 7, 2): full hex UV with centroid at vertex 6
    # hi[mode][c2][vertex][uv]  — vertices 0..5 are hex boundary, vertex 6 is centroid
    f.write('/* H9P.hi[mode][c2][vertex][u/v]: integer UV hex template (vertex 6 = centroid)\n')
    f.write('   shape (2, 3, 7, 2) — mode in {0,1}, c2 in {0,1,2}, vertex in {0..6} */\n')
    f.write('static const int H9_HI[2][3][7][2] = {\n')
    for mode in range(2):
        f.write(f'    /* mode {mode} */ {{\n')
        for c2 in range(3):
            verts = ', '.join(f'{{{int(hi[mode,c2,v,0])}, {int(hi[mode,c2,v,1])}}}' for v in range(7))
            f.write(f'        /* c2={c2} */ {{{verts}}},\n')
        f.write('    },\n')
    f.write('};\n\n')

    # Convenience: number of children
    f.write(f'#define H9_N_CHILDREN 9  /* 9 cells per supercell */\n')
    f.write(f'#define H9_N_OCTANTS  8\n')
    f.write(f'#define H9_N_C2       3\n')

print(f'Written: {OUT}')

# Sanity dump
print(f'U1={U1:.15g}  V3={V3:.15g}')
print(f'H9R.downs = {list(int(x) for x in downs)}')
print(f'H9R.ups   = {list(int(x) for x in ups)}')
print(f'mode_child_dn = {list(int(x) for x in mode_child_dn)}')
print(f'mode_child_up = {list(int(x) for x in mode_child_up)}')
print(f'H9O.oid_mo = {list(int(x) for x in oid_mo)}')
print(f'H9O.oid_nb =\n{oid_nb}')
print(f'H9P.hi[0] (mode-0) =\n{hi[0]}')
print(f'H9P.hi[1] (mode-1) =\n{hi[1]}')
print(f'mode_ofs_dn (U*3) =\n{mode_ofs_dn}')
print(f'mode_ofs_up (U*3) =\n{mode_ofs_up}')
