#!/usr/bin/env python3
"""
gen_h9_lattice_consts.py — emit `h9_lattice_consts.h`, the small C++ header
containing the lookup tables that the C++ port of `tri_mesh` needs.

Source of truth: `hhg9.h9.lattice.H9C`, `hhg9.h9.region.H9R`, `hhg9.h9.polygon.H9P`.

Output (constexpr, ~400 bytes):
    H9_KIDS[parent_mode][k]   -> {child_mode, off_x, off_y}     k in [0..8]
    H9_SV  [mode][vertex]     -> {x, y}                          vertex in [0..2]

The arrays in this generated header are the ONLY parts of the Python H9
machinery the C++ extension needs in order to rebuild the L5 lattice (266,815
vertices, 531,441 triangles) without runtime dependencies.

Run from hex9_cli source directory:
    python gen_h9_lattice_consts.py
"""

import os
import sys
import datetime
import numpy as np

from hhg9.h9 import H9C, H9R
from hhg9.h9.polygon import H9P

OUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        'h9_lattice_consts.h')


def fmt_double(v: float) -> str:
    """Format float64 with enough precision to round-trip the bit pattern."""
    return f"{float(v):.17g}"


def emit_kids_row(parent_mode: int, kids_ids) -> str:
    lines = []
    for k in kids_ids:
        m = int(H9C.mode[int(k)])
        ox, oy = H9C.off_xy[int(k)]
        lines.append(
            f"  /* k=0x{int(k):02x} */ {{ {m}, {fmt_double(ox)}, {fmt_double(oy)} }}")
    return ",\n".join(lines)


def emit_sv_row(mode: int) -> str:
    lines = []
    for v in range(3):
        x, y = H9P.sv[mode, v]
        lines.append(f"  {{ {fmt_double(x)}, {fmt_double(y)} }}")
    return ",\n".join(lines)


def main():
    when = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    header = f"""/* h9_lattice_consts.h — AUTO-GENERATED by gen_h9_lattice_consts.py
 *                       DO NOT EDIT BY HAND.
 *
 * Generated: {when}
 *
 * Lookup tables for the analytic L5 lattice generator (port of
 * hhg9/h9/polygon.py:tri_grid / tri_mesh).  ~400 bytes total.
 *
 *   H9_KIDS[parent_mode][k] : child mode + (x, y) offset of child k
 *   H9_SV  [mode][vertex]   : unit-triangle vertex (x, y) for mode 0/1
 *
 * Iteration order over k matches Python H9R.downs / H9R.ups so that
 * `region_grid` produces identical output to the Python reference.
 *
 *   downs (mode 0 children) : {[int(x) for x in H9R.downs]}
 *   ups   (mode 1 children) : {[int(x) for x in H9R.ups]}
 */
#ifndef H9_LATTICE_CONSTS_H
#define H9_LATTICE_CONSTS_H

#include <cstdint>

namespace h9 {{

struct LatticeKid {{
    std::uint8_t mode;
    double off_x;
    double off_y;
}};

inline constexpr LatticeKid H9_KIDS[2][9] = {{
  {{ /* parent_mode = 0 (down) */
{emit_kids_row(0, H9R.downs)}
  }},
  {{ /* parent_mode = 1 (up) */
{emit_kids_row(1, H9R.ups)}
  }}
}};

inline constexpr double H9_SV[2][3][2] = {{
  {{ /* mode = 0 (down) unit-triangle vertices */
{emit_sv_row(0)}
  }},
  {{ /* mode = 1 (up) unit-triangle vertices */
{emit_sv_row(1)}
  }}
}};

}} // namespace h9

#endif /* H9_LATTICE_CONSTS_H */
"""

    with open(OUT_PATH, 'w') as fh:
        fh.write(header)
    print(f"Wrote {OUT_PATH} ({len(header)} bytes)")


if __name__ == '__main__':
    sys.exit(main())
