//! Raw FFI bindings to **libhex9** — the Hex9 / H9 aperture-9 hexagonal DGGS.
//!
//! Generated by `bindgen` over `hex9_c.h` at build time (see `build.rs`); the
//! static library is built from the adjacent CMake project. This crate is
//! `unsafe` and unopinionated — safe, idiomatic wrappers live in the GeoPlegma
//! `hex9` DGGRS adapter, which is the only intended consumer.
//!
//! Every public Hex9 UUID is a 16-byte (`[u8; 16]`) self-contained address; the
//! human/text form is `"<x_list>.<T>"` (e.g. `"43527.4"`). The deepest layer is
//! reported by [`hex9_lmax`] (30 on the default reclaimed layout, 29 legacy).

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    /// Smoke-test that the static library links and the warp initialises.
    #[test]
    fn links_and_reports_lmax() {
        unsafe {
            let mut err = [0i8; 256];
            // 0 = success (the embedded warp blob is always present).
            assert_eq!(hex9_warp_init(err.as_mut_ptr(), err.len()), 0);
            let lmax = hex9_lmax();
            assert!(lmax == 29 || lmax == 30, "unexpected lmax {lmax}");

            // Encode a point and confirm a non-degenerate 16-byte UUID comes back.
            let mut uuid = [0u8; 16];
            assert_eq!(hex9_encode(-3.19, 55.95, uuid.as_mut_ptr()), 0);
            assert_ne!(uuid, [0u8; 16]);
        }
    }
}
