//! Raw FFI bindings to **libhex9** — the Hex9 / H9 aperture-9 hexagonal DGGS.
//!
//! Generated by `bindgen` over `hex9_c.h` at build time (see `build.rs`); the
//! static library is built from the adjacent CMake project. This crate is
//! `unsafe` and unopinionated — safe, idiomatic wrappers live in the GeoPlegma
//! `hex9` DGGRS adapter, which is the only intended consumer.
//!
//! Every public Hex9 UUID is a 16-byte (`[u8; 16]`) self-contained address; the
//! human/text form is `"<x_list>.<T>"` (e.g. `"43527.4"`). The deepest layer is
//! reported by [`hex9_lmax`] (30 on the default reclaimed layout, 29 legacy).
//!
//! Beyond point addressing the ABI covers the Hamiltonian curve (`hex9_curve*`
//! — sortable curve-uuids, numeric indices, exact prefix coarsening), the
//! warped octahedral cartesian CRS `w_oct` used as the 3D point-cloud storage
//! baseline (`hex9_boct_to_woct` / `hex9_woct_to_boct`), and the lineage /
//! ownership hierarchy relations.
//!
//! # Warp regime
//!
//! An address is only meaningful alongside the projection that produced it,
//! and nothing in the 16 bytes records which projection that was.
//!
//! There is one regime: the authalic latitude series feeding a unit-sphere
//! core under the Sphere-L6 wedge-fold field. libhex9 2.0.0 removed the
//! earlier WGS84-trained regime rather than let a point carry two
//! indistinguishable addresses — but that change moves addresses from about
//! layer 7 downward. Addresses minted by 1.x must be re-derived from source
//! geometry, never remapped by decode-and-re-encode. See
//! `docs/warp-regimes.md`.
//!
//! [`hex9_warp_init`] must succeed before any addressing call; on failure the
//! core falls back to an identity field whose output is *not* a Hex9 address.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    /// Smoke-test that the static library links and the warp initialises.
    #[test]
    fn links_and_reports_lmax() {
        unsafe {
            let mut err = [0i8; 256];
            // 0 = success (the embedded warp blob is always present).
            assert_eq!(hex9_warp_init(err.as_mut_ptr(), err.len()), 0);
            let lmax = hex9_lmax();
            assert!(lmax == 29 || lmax == 30, "unexpected lmax {lmax}");

            // Encode a point and confirm a non-degenerate 16-byte UUID comes back.
            let mut uuid = [0u8; 16];
            assert_eq!(hex9_encode(-3.19, 55.95, uuid.as_mut_ptr()), 0);
            assert_ne!(uuid, [0u8; 16]);
        }
    }
}
