#!/usr/bin/env python3
# Part of the Hex9 (H9) Project
# Copyright ©2026, Ben Griffin
# Licensed under the Apache License, Version 2.0

"""Generate core/h9_fold_tables.h from the hhg9 canonical tables.

These are the tables the address-space canonical-ancestor fold needs
(h9kring::h9_cell_fold_uuid): the region_neighbours cascade tables, the
terminal-c2 resolution with its nearest-group fallback baked in, and the
classifier-cell y-mirror involution for octant-crossing folds. hhg9 is the
single source of truth — regenerate rather than edit.

Run:  python tools/gen_fold_tables.py   (writes core/h9_fold_tables.h)
"""
import os
import numpy as np


def fmt(arr, per_line=16):
    flat = np.asarray(arr, dtype=np.uint8).ravel()
    lines = []
    for i in range(0, len(flat), per_line):
        lines.append('    ' + ', '.join(f'{v:3d}' for v in flat[i:i + per_line]) + ',')
    body = '\n'.join(lines).rstrip(',')
    return body


def main():
    from hhg9.h9 import H9C, H9K, H9R
    from hhg9.h9.classifier import classify_cell

    cmc2n = np.asarray(H9R.cmc2n, dtype=np.uint8)            # (96, 2, 3, 2)
    child = np.asarray(H9R.child, dtype=np.uint8)            # (2, 3, 3)
    proto = np.asarray(H9R.proto, dtype=np.uint8)            # (2,)
    cmode = np.asarray(H9C.mode, dtype=np.uint8)             # (96,)
    mcc2 = np.asarray(H9R.mcc2, dtype=np.uint8)              # (2, 96)
    bad = np.uint8(H9R.invalid_region)
    off = H9C.off_xy

    # Terminal c2 with region_neighbours' nearest-c2-group fallback baked in.
    term_c2 = mcc2.copy()
    for imo in range(2):
        cells_mode = np.asarray(H9C.c2[imo]).reshape(-1)
        k = np.asarray(H9C.c2[imo]).shape[1]
        for t in range(term_c2.shape[1]):
            if term_c2[imo, t] != bad:
                continue
            if t == bad:
                term_c2[imo, t] = 0
                continue
            d2 = np.sum((off[cells_mode] - off[t]) ** 2, axis=1)
            term_c2[imo, t] = np.uint8(int(np.argmin(d2)) // k)

    # Classifier-cell y-mirror (octant-seam frame flip): chains mirror
    # entry-wise because every level's frame transform commutes with y->-y.
    ymirror = np.asarray(classify_cell(H9K.R3 * off[:, 0], -off[:, 1]),
                         dtype=np.uint8)

    out = os.path.join(os.path.dirname(__file__), '..', 'core',
                       'h9_fold_tables.h')
    with open(out, 'w') as f:
        f.write(
            "/* Generated by tools/gen_fold_tables.py from hhg9 — do not edit.\n"
            " *\n"
            " * Tables for the address-space canonical-ancestor fold\n"
            " * (h9kring::h9_cell_fold_uuid): region_neighbours' cascade in\n"
            " * classifier-cell (c_dig) space, terminal-c2 resolution with the\n"
            " * nearest-group fallback baked in, and the y-mirror involution\n"
            " * used when a fold crosses an octant seam. */\n"
            "#pragma once\n"
            "#include <stdint.h>\n\n"
            f"#define H9F_INVALID {int(bad)}u\n\n"
            "/* [cell][parent_mode][c2] -> {neighbour cell, its parent_mode} */\n"
            "static const uint8_t H9F_CMC2N[96][2][3][2] = {\n"
            f"{fmt(cmc2n, 12)}\n}};\n\n"
            "/* [mode][c2] -> terminal cell (h9r.child[mode][c2][2]) */\n"
            "static const uint8_t H9F_CHILD_TRM[2][3] = {\n"
            f"{fmt(child[:, :, 2], 3)}\n}};\n\n"
            "/* proto cell per mode */\n"
            "static const uint8_t H9F_PROTO[2] = {\n"
            f"{fmt(proto, 2)}\n}};\n\n"
            "/* intrinsic mode per classifier cell */\n"
            "static const uint8_t H9F_CMODE[96] = {\n"
            f"{fmt(cmode)}\n}};\n\n"
            "/* [mode][terminal cell] -> c2, nearest-group fallback baked in */\n"
            "static const uint8_t H9F_TERM_C2[2][96] = {\n"
            f"{fmt(term_c2)}\n}};\n\n"
            "/* classifier-cell y-flip involution (octant-seam frame flip) */\n"
            "static const uint8_t H9F_YMIRROR[96] = {\n"
            f"{fmt(ymirror)}\n}};\n"
        )
    print(f'wrote {os.path.normpath(out)}')


if __name__ == '__main__':
    main()
