#!/usr/bin/env python3
"""Generate an inline-asm-free replacement TU for core/h9_warp_embedded.cpp.

The core embeds the warp blob with `.incbin` inline asm, which Emscripten's
wasm backend rejects ("relocations ... only supported in metadata sections")
and MSVC x64 cannot express at all (no __asm__). This emits the same h9::
symbols from plain C++ data.

Usage: gen_warp_embed.py <blob path> <output .cpp path> [--array]

Default is a string-literal initializer (fast for clang/gcc). --array emits a
brace initializer instead, for MSVC, whose string literals cap at 64 KB.
"""
import sys


def main() -> int:
    src, dst = sys.argv[1], sys.argv[2]
    array_style = "--array" in sys.argv[3:]
    with open(src, "rb") as f:
        data = f.read()
    with open(dst, "w") as f:
        f.write("/* GENERATED by scripts/gen_warp_embed.py — do not edit.\n"
                " * Inline-asm-free stand-in for core/h9_warp_embedded.cpp (.incbin). */\n")
        f.write('#include "h9_warp_embedded.h"\n#include <cstddef>\n\n')
        if array_style:
            f.write("static const unsigned char blob[] = {\n")
            for i in range(0, len(data), 4096):
                f.write(",".join("%d" % b for b in data[i:i + 4096]) + ",\n")
            f.write("};\n")
            size_expr = "sizeof(blob)"
        else:
            f.write("static const unsigned char blob[] =\n")
            for i in range(0, len(data), 16384):
                f.write('"' + "".join("\\x%02x" % b for b in data[i:i + 16384]) + '"\n')
            # string literals append a NUL that is not part of the blob
            f.write(";\n")
            size_expr = "sizeof(blob) - 1"
        f.write("\nnamespace h9 {\n")
        f.write("const unsigned char *const EMBEDDED_WARP_DATA = blob;\n")
        f.write(f"const std::size_t          EMBEDDED_WARP_SIZE = {size_expr};\n")
        f.write("}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
