#!/usr/bin/env python3
"""Generate a wasm-safe replacement TU for core/h9_warp_embedded.cpp.

The core embeds the warp blob with `.incbin` inline asm, which Emscripten's
wasm backend rejects ("relocations ... only supported in metadata sections").
This emits the same h9:: symbols from a plain string-literal initializer,
which the compiler handles quickly even at ~19 MB.

Usage: gen_warp_embed.py <blob path> <output .cpp path>
"""
import sys


def main() -> int:
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "rb") as f:
        data = f.read()
    chunk = 16384
    with open(dst, "w") as f:
        f.write("/* GENERATED by scripts/gen_warp_embed.py — do not edit.\n"
                " * Wasm-safe stand-in for core/h9_warp_embedded.cpp (.incbin). */\n")
        f.write('#include "h9_warp_embedded.h"\n#include <cstddef>\n\n')
        f.write("static const unsigned char blob[] =\n")
        for i in range(0, len(data), chunk):
            part = data[i:i + chunk]
            f.write('"' + "".join("\\x%02x" % b for b in part) + '"\n')
        f.write(";\n\nnamespace h9 {\n")
        f.write("const unsigned char *const EMBEDDED_WARP_DATA = blob;\n")
        # string literals append a NUL that is not part of the blob
        f.write("const std::size_t          EMBEDDED_WARP_SIZE = sizeof(blob) - 1;\n")
        f.write("}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
