#!/usr/bin/env python3
"""
export_warp_test_vecs.py — C++ validation header for the authalic warp.

Emits h9_warp_test_vecs.h: a table of known forward-warp results

    (braw_x, braw_y, oct_mode)  →  (bary_x, bary_y)

so the C++ port can sanity-check h9_warp after any CT-mesh / coefficient update.
Distinct from generate_test_cases.py, which checks the full UUID pipeline; this
isolates the warp layer alone.

Reference map (b_raw → b_oct), matching scipy AuthalicWarp.do():

    phi  = h9_edge_blend(braw)                  # see h9_math.h
    bary = braw + phi * CT_{dst-src}(braw)

CT_{dst-src} is the scipy CloughTocher2D interpolant of the displacement field
(dst - src) over the equator-ghost-padded source points — the exact field whose
19 Bernstein coefficients export_ct_mesh.py bakes into h9_wgs84_ct_mesh.h. The
C++ h9_ct_eval matches it to ~1e-10, so compare with tol ~1e-9.

Apex and on-lateral rows have phi = 0 → bary == braw exactly: those rows double
as a check that the C++ edge-blend is wired correctly.

IMPORTANT: EDGE_BAND below must equal H9_CT_EDGE_BAND in h9_math.h. The header
records the band it was generated with; a mismatch shows up as failures on the
'near lateral' / 'near apex' rows only.

Run from the hex9_cli source directory:
    python export_warp_test_vecs.py
"""
import os
import math
import datetime
import numpy as np
from scipy.interpolate import CloughTocher2DInterpolator, NearestNDInterpolator

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
NPZ_PATH   = os.path.join(SCRIPT_DIR, 'WGS84_l5_warp_data.npz')
OUT_PATH   = os.path.join(SCRIPT_DIR, 'h9_warp_test_vecs.h')

# Must match H9_CT_EDGE_BAND in h9_math.h.
EDGE_BAND = 0.03

R3   = math.sqrt(3.0)
W_   = math.sqrt(6.0) / 3.0          # Ẇ = √6/3 = H9_2H_3
Y_EQ = math.sqrt(6.0) / 6.0          # equator y

# Mode-0 triangle corners: apex (pole), right-base, left-base.
APEX  = np.array([0.0,                 -math.sqrt(6.0) / 3.0])
BASER = np.array([ math.sqrt(2.0) / 2.0, math.sqrt(6.0) / 6.0])
BASEL = np.array([-math.sqrt(2.0) / 2.0, math.sqrt(6.0) / 6.0])
CORNERS = np.array([APEX, BASER, BASEL])

# Barycentric weights (apex, right-base, left-base) + label.
SAMPLES = [
    ((1 / 3, 1 / 3, 1 / 3), 'interior centroid'),
    ((0.60, 0.30, 0.10),    'interior off-centre'),
    ((0.20, 0.50, 0.30),    'interior near base'),
    ((0.97, 0.015, 0.015),  'near apex (pole vertex)'),
    ((1.00, 0.00, 0.00),    'apex exactly (identity)'),
    ((0.50, 0.50, 0.00),    'on right lateral edge (identity)'),
    ((0.50, 0.00, 0.50),    'on left lateral edge (identity)'),
    ((0.50, 0.488, 0.012),  'near right lateral (seam)'),
    ((0.50, 0.012, 0.488),  'near left lateral (seam)'),
    ((0.02, 0.96, 0.02),    'near right base vertex'),
    ((0.02, 0.02, 0.96),    'near left base vertex'),
    ((0.02, 0.49, 0.49),    'near base-edge midpoint'),
]


def edge_blend(xy):
    """φ — identical to h9_edge_blend() in h9_math.h."""
    d = (xy[:, 1] - R3 * np.abs(xy[:, 0]) + W_) * 0.5
    t = np.clip(d / EDGE_BAND, 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)


def main():
    # Use the production AuthalicWarp as the ground truth so the exported
    # vectors track exactly what AuthalicWarp.do() produces in the rest of
    # the codebase (and what the C++ port matches to 3 nm). The old
    # edge_blend / phi-smoothstep approach is gone — it was replaced by a
    # hard identity bypass at the exact lateral-edge band; see
    # octahedral_barycentric.py:316-339.
    from hhg9.domains.octahedral_barycentric import AuthalicWarp
    print(f'Loading {os.path.normpath(NPZ_PATH)} ...')
    warp = AuthalicWarp(NPZ_PATH)

    def warp_do(braw, mode):
        return warp.do(braw.reshape(1, 2), mo=mode)[0]

    rows = []
    for w, label in SAMPLES:
        braw = np.array(w, dtype=np.float64) @ CORNERS
        for mode in (0, 1):
            src_pt = braw.copy()
            if mode == 1:
                src_pt[1] = -src_pt[1]
            bary = warp_do(braw if mode == 0 else
                           np.array([braw[0], -braw[1]]), mode)
            rows.append((src_pt[0], src_pt[1], mode, bary[0], bary[1],
                         f'{label} [mode {mode}]'))

    write_header(rows)
    print(f'Wrote {len(rows)} vectors → {os.path.normpath(OUT_PATH)}')
    for bx, by, mode, wx, wy, label in rows:
        d = math.hypot(wx - bx, wy - by)
        print(f'  [{mode}] {label:36s} disp={d:.3e}')


def write_header(rows):
    L = [
        '/* h9_warp_test_vecs.h — AUTO-GENERATED by export_warp_test_vecs.py — DO NOT EDIT',
        ' *',
        f' * Generated : {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}',
        ' * Source    : WGS84_l5_warp_data.npz',
        f' * Edge band : {EDGE_BAND:.17g}  (MUST equal H9_CT_EDGE_BAND in h9_math.h)',
        ' *',
        ' * Forward-warp reference vectors:  bary = braw + phi(braw)*CT(braw).',
        ' * The C++ b_raw->b_oct warp must reproduce (bary_x, bary_y) within ~1e-9.',
        ' * Apex / on-lateral rows have phi=0, so bary == braw exactly.',
        ' */',
        '#ifndef H9_WARP_TEST_VECS_H',
        '#define H9_WARP_TEST_VECS_H',
        '',
        'struct H9WarpTestVec {',
        '    double      braw_x, braw_y;   /* input  b_raw coordinate   */',
        '    int         oct_mode;         /* 0 = down, 1 = up          */',
        '    double      bary_x, bary_y;   /* expected b_oct coordinate */',
        '    const char *label;',
        '};',
        '',
        f'static const int H9_WARP_TEST_N = {len(rows)};',
        '',
        'static const H9WarpTestVec H9_WARP_TEST_VECS[] = {',
    ]
    for bx, by, mode, wx, wy, label in rows:
        L.append(f'    {{ {bx:+.17g}, {by:+.17g}, {mode}, '
                 f'{wx:+.17g}, {wy:+.17g}, "{label}" }},')
    L += ['};', '', '#endif /* H9_WARP_TEST_VECS_H */', '']
    with open(OUT_PATH, 'w') as f:
        f.write('\n'.join(L))


if __name__ == '__main__':
    main()
